// Conjuntos de agentes do Mira. Módulo sem efeitos colaterais, para ser
// importado tanto pela instalação quanto pela atualização.

export const PIPELINE_CORE = [
  'mira-new',
  'mira-references',
  'mira-extract',
  'mira-planner',
  'mira-copywriter',
  'mira-builder',
  'mira-animator',
  'mira-size-animator',
  'mira-animated-metaphor',
  'mira-3d',
  'mira-qrcode',
  'mira-webview',
  'mira-survey',
  'mira-quiz',
  'mira-tactics',
  'mira-remote-control',
  'mira-image',
  'mira-svg-morph',
  'mira-icon-morph',
  'mira-svg-animator',
  'mira-animated-typing',
  'mira-squared',
  'mira-vertical',
  'mira-thirds',
  'mira-studio',
  'mira-studio-full',
  'mira-transition-dissolve',
  'mira-slide-to-video',
  'mira-offline',
  'mira-validator',
  'mira-get-videos',
  '_shared',
];

export const VISUAL_TEAM = [
  'mira-visuals',
  'mira-image-prompt',
  'mira-img-animator',
  'mira-image-template',
  'mira-chart',
  'mira-chart-race',
];
